src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommandeRepository::class)]
class Commande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?\DateTime $startAt = null;

    #[ORM\Column]
    private ?\DateTime $endAT = null;

    #[ORM\Column]
    private ?float $prix = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $createdAt = null;


    #[ORM\ManyToOne(inversedBy: 'commandes')]
    private ?User $User = null;

    #[ORM\ManyToOne(inversedBy: 'commandes')]
    private ?Chambre $Chambre = null;

 

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStartAt(): ?\DateTime
    {
        return $this->startAt;
    }

    public function setStartAt(\DateTime $startAt): self
    {
        $this->startAt = $startAt;

        return $this;
    }

    public function getEndAT(): ?\DateTime
    {
        return $this->endAT;
    }

    public function setEndAT(\DateTime $endAT): self
    {
        $this->endAT = $endAT;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }



    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getChambre(): ?Chambre
    {
        return $this->Chambre;
    }

    public function setChambre(?Chambre $Chambre): self
    {
        $this->Chambre = $Chambre;

        return $this;
    }


}

templates/_flash.html.twig
      
      {% for message in app.flashes('success') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}

templates/_footer.html.twig
    <!-- FOOTER -->
    <footer class="py-8 py-md-11 bg-dark">
      <div class="container">
        <div class="row">
          <div class="col-12 col-md-4 col-lg-3">
    
            <!-- Brand -->
            {# <img src="./assets/img/brand.svg" alt="..." class="footer-brand img-fluid mb-2"> #}
    
            <!-- Text -->
            <p class="text-gray-700 mb-2">
              A better way to build.
            </p>
    
            <!-- Social -->
            <ul class="list-unstyled list-inline list-social mb-6 mb-md-0 ms-4">
              <li class="list-inline-item list-social-item me-3">
                <a href="https://www.instagram.com" class="text-decoration-none">
                  <img src="{{asset('images/instagram.png')}}" class="list-social-icon" alt="">
                </a>
              </li>
              <li class="list-inline-item list-social-item me-3">
                <a href="https://fr-fr.facebook.com/login.php/" class="text-decoration-none">
                  <img src="{{asset('images/facebook.png')}}" class="list-social-icon" alt="">
                </a>
              </li>
              <li class="list-inline-item list-social-item me-3">
                <a href="https://fr.linkedin.com" class="text-decoration-none">
                  <img src="{{asset('images/linkedin.png')}}" class="list-social-icon" alt="">
                </a>
              </li>
              <li class="list-inline-item list-social-item">
                <a href="https://twitter.com" class="text-decoration-none">
                  <img src="{{asset('images/logo-twitter.png')}}" class="list-social-icon" alt="">
                </a>
              </li>
            </ul>
    
          </div>
          <div class="col-6 col-md-4 col-lg-2">
    
            <!-- Heading -->
            <h6 class="fw-bold text-uppercase text-gray-700">
              Products
            </h6>
    
            <!-- List -->
            <ul class="list-unstyled text-muted mb-6 mb-md-8 mb-lg-0">
              <li class="mb-3">
                <a href="#!" class="text-reset">
                  L'HOTEL
                </a>
              </li>
              <li class="mb-3">
                <a href="https://goo.gl/maps/yUEe1i4DAkuFgAmf6" class="text-reset">
                  Plan
                </a>
              </li>
              <li class="mb-3">
               <a href="#!" class="text-reset">
              <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2624.6401911606995!2d2.3020784!3d48.865071199999996!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66fdd0dd39a4d%3A0x508194b82b12f012!2s1%20Av.%20Montaigne%2C%2075008%20Paris!5e0!3m2!1sfr!2sfr!4v1661434517222!5m2!1sfr!2sfr"
               width="100" height="100" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"> </iframe>
               
                </a>
              </li>
              <li class="mb-3">
                <a href="#!" class="text-reset">
                  Contact
                </a>
              </li>
        
            </ul>
    
          </div>
          <div class="col-6 col-md-4 col-lg-2">
    
            <!-- Heading -->
            <h6 class="fw-bold text-uppercase text-gray-700">
              Services
            </h6>
    
            <!-- List -->
            <ul class="list-unstyled text-muted mb-6 mb-md-8 mb-lg-0">
              <li class="mb-3">
                <a href="#!" class="text-reset">
                  Liens divers
                </a>
              </li>
              <li class="mb-3">
                <a href="#!" class="text-reset">
                  Mentions Légales
                </a>
              </li>
              <li class="mb-3">
                <a href="https://www.mediacc.com/l-agence/conditions-generales-de-vente-developpement-de-site-web-extranet" class="text-reset">
                  Conditions Générales de Vente
                </a>
              </li>
              <li>
                <a href="" class="text-reset">
                  Plan du site
                </a>
              </li>
            </ul>
    
          </div>
          <div class="col-6 col-md-4 offset-md-4 col-lg-2 offset-lg-0">
    
            <!-- Heading -->
            <h6 class="fw-bold text-uppercase text-gray-700">
              Connect
            </h6>
    
            <!-- List -->
            <ul class="list-unstyled text-muted mb-0">
              <li class="mb-3">
                <a href="#!" class="text-reset">
                  Imprimer la page
                </a>
              </li>
              <li class="mb-3">
                <a href="#!" class="text-reset">
                  S'inscrire à la newsletter
                </a>
              </li>
              <li class="mb-3">
                <a href="#!" class="text-reset">
              Partager
                </a>
              </li>
              <li class="mb-3">
                <a href="#!" class="text-reset">
                  Documentation
                </a>
              </li>
           
         
           
            </ul>
    
          </div>
          <div class="col-6 col-md-4 col-lg-2">
    
            <!-- Heading -->
            <h6 class="fw-bold text-uppercase text-gray-700">
              Legal
            </h6>
    
            <!-- List -->
            <ul class="list-unstyled text-muted mb-0">
              <li class="mb-3">
                <a href="https://www.parisinfo.com" class="text-reset">
                  Actualités
                </a>
              </li>
           
         
            </ul>
    
          </div>
        </div> <!-- / .row -->
      </div> <!-- / .container -->
    </footer>

templates/_navbar.html.twig
<nav class="navbar navbar-expand-lg bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand text-white" href="{{path('app_home')}}">Hotel/Restaurant</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        
      
      <ul class="navbar-nav">
    
        
        <li class="nav-item">
          <a class="nav-link active text-white" aria-current="page" href="{{path('app_register')}}">S'inscrire</a>
        </li>
          <li class="nav-item">
          <a class="nav-link text-white" href="{{path('app_login')}}">Se Connecter</a>
        </li>
         
        {% if app.user %}
          
      
      
        <li class="nav-item">
          <a class="nav-link text-white" href="{{path('app_logout')}}">Se Déconnecter</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="{{path('app_avis_index')}}">Livre d'Or</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="{{path('app_commande_index')}}">Réservation</a>
        </li>
     
        <li class="nav-item">
          <a class="nav-link text-white" href="{{path('app_profil')}}">Profil</a>
        </li>
     
         {% endif %}
    
         {% if is_granted('ROLE_ADMIN') %}
        <li class="nav-item">
          <a class="nav-link text-white" href="{{path('app_chambre_index')}}">Chambre</a>
        </li>
     
         {% endif %}
           <li class="nav-item">
          <a class="nav-link text-success fw-bold text-jistify text-right" href="{{path('app_restaurant')}}">RESTAURANT</a>
        </li>
           <li class="nav-item">
          <a class="nav-link text-danger fw-bold text-jistify text-right" href="{{path('app_spa')}}">SPA</a>
        </li>
      </ul>
      
    </div>
  </div>
</nav>

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        <link rel="stylesheet" href="	https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="{{asset('css/style.css')}}">
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
       {% include "_navbar.html.twig" %}
       {% include "_flash.html.twig" %}
     
    
     {% block body %}
    
    {% block titre %}{% endblock %}
    

   
       {% endblock %}
       <footer>
       {% block footer %}
         {% include "_footer.html.twig" %}
         {% endblock %}
         </footer>
   
    </body>



   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
   <script src="{{asset('js/script.js')}}"></script>
     
</html>